server:
  port: 8761
eureka:
  client:
    registerWithEureka: false  #是否将eureka自身作为应用注册到eureka注册中心
    fetchRegistry: false       #为true时，可以启动，但报异常：Cannot execute request on any known server
    service-url:
      defaultZone: http://kation:123456@localhost:8761/eureka
security:
  user:
    name: kation
    password: 123456
  server:
    servlet:
      context-path: /manage
    port: 8081
    address: 127.0.0.1